android.useAndroidX=true
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m --add-opens jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
systemProp.file.encoding=utf-8

# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
#my configuration
android.nonTransitiveRClass=true
android.enableJetifier=true

org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
#android.enableBuildCache=true
org.gradle.caching=true
org.gradle.unsafe.configuration-cache=true

# Kotlin/KAPT incremental build optimizations
kotlin.incremental=true
kapt.incremental.apt=true
