android.useAndroidX=true
org.gradle.jvmargs=-Xmx6144M -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -Dfile.encoding=UTF-8 --add-opens jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
systemProp.file.encoding=utf-8

# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
#my configuration
android.nonTransitiveRClass=true
#android.enableJetifier=true

org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
#android.enableBuildCache=true
org.gradle.caching=true

# Kotlin/KAPT incremental build optimizations
kotlin.incremental=true
kotlin.compiler.execution.strategy=daemon
kotlin.daemon.jvmargs=-Xmx2048m
kapt.incremental.apt=true
